# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: 'Getting started'
  link: '/getting-started'
- label: API
  items:
    - label: useGrid
      link: /api/useGrid
    - label: useGrids
      link: /api/useGrids
    - label: core
      link: /api/core
- label: Examples
  items:
    - label: Basic
      link: /example/basic
    - label: Basic without virtualization
      link: /example/basic-without-virtualization
    - label: 'useGrids: Pinned Column'
      link: /example/use-grids-pinned-column
    - label: Dynamic height
      link: /example/dynamic-height
